Empty string check when setting a property.
spatie/schema-org pull request #153
Opened 2020-10-17 10:38 UTC by jose-gomez-evinex

Update BaseType.php
Added empty string check when setting a property.
Fixes issue #151

2020-10-17 12:30 UTC, Gummibeer requested changes
Thanks for your PR!
The changes should be done in the generator template as they will otherwise be reverted the next time we generate the source code.

2020-10-17 12:30 UTC, Gummibeer commented on src/BaseType.php
> +        if ($value !== null && $value !== ''){
```suggestion
        if ($value !== null && $value !== '') {
```

2020-10-17 12:59 UTC, jose-gomez-evinex commented
Thanks and sorry about that. I should have be more familiar with the project before submiting any request. Also, I'm still learning how Github works 😅.

2020-10-17 13:02 UTC, Gummibeer approved these changes

2020-10-17 13:03 UTC, Gummibeer commented
Everything fine! 😉 That's why we review PRs before merging. 😊

Thanks for the quick fix. I'm on the road right now - but seems good.
Will check in detail, merge and release later. 🎉

2020-10-22 10:51 UTC, Gummibeer approved these changes

2020-10-22 10:51 UTC, merged

2020-10-22 10:57 UTC, Gummibeer commented
https://github.com/spatie/schema-org/releases/tag/3.1.1